namespace BlackPearl.Prism.Core.WPF.CodeGenerator
{
    internal static class CommentHeaderGenerator
    {
        internal static void GenerateCommentHeader(this ViewModelDocumentBuilder vmBuilder)
        {
            vmBuilder.AppendLine("// <auto-generated>");
            vmBuilder.AppendLine("//   BlackPearl.Prism.Core - WPF");
            vmBuilder.AppendLine("//   This generator is based on MvvmGen, a tool created by Thomas Claudius Huber (https://www.thomasclaudiushuber.com)");
            vmBuilder.AppendLine("// </auto-generated>");
        }
    }
}
